version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_VERSION:-latest}
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:${CP_VERSION:-latest}
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  go-producer:
    image: ryanp/confluent-kafka-go-example 
    command: -P -s 1024 -d 1m /conf/producer.properties
    volumes:
      - ./src/conf/:/conf
